services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: monMotDePasseSuperSecret
      MYSQL_DATABASE: test
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "7070:3306"