services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: monMotDePasseSuperSecret
      MYSQL_DATABASE: test
    volumes:
      - /public/stalbou ./data:/var/lib/mysql
    ports:
      - "3306:3306"
